// 菜品池数据（附件3）：按 早餐 / 午餐 / 晚餐 分类
// 分类可随时在「管理员后台 → 食物库管理」中增删改

export const FOODS = [
  // ===== 早餐 breakfast =====
  { name: '小米粥', category: 'breakfast' },
  { name: '杂粮馒头', category: 'breakfast' },
  { name: '韭菜饺子', category: 'breakfast' },
  { name: '鲜肉馄饨', category: 'breakfast' },
  { name: '鸡蛋炒面', category: 'breakfast' },
  { name: '红烧牛肉面', category: 'breakfast' },
  { name: '蛋炒饭', category: 'breakfast' },
  { name: '牛肉炒粉', category: 'breakfast' },
  { name: '炒河粉', category: 'breakfast' },

  // ===== 午餐 lunch =====
  { name: '青椒炒肉丝', category: 'lunch' },
  { name: '鱼香肉丝', category: 'lunch' },
  { name: '木耳炒肉片', category: 'lunch' },
  { name: '芹菜炒牛肉', category: 'lunch' },
  { name: '小炒黄牛肉', category: 'lunch' },
  { name: '土豆烧排骨', category: 'lunch' },
  { name: '红烧鸡块', category: 'lunch' },
  { name: '辣子鸡', category: 'lunch' },
  { name: '宫保鸡丁', category: 'lunch' },
  { name: '香菇滑鸡', category: 'lunch' },
  { name: '啤酒鸭', category: 'lunch' },
  { name: '香干炒肉', category: 'lunch' },
  { name: '蒜香排骨', category: 'lunch' },
  { name: '梅菜扣肉', category: 'lunch' },
  { name: '回锅肉', category: 'lunch' },
  { name: '水煮肉片', category: 'lunch' },
  { name: '毛血旺', category: 'lunch' },
  { name: '青椒炒猪肝', category: 'lunch' },
  { name: '洋葱炒牛肉', category: 'lunch' },
  { name: '韭菜炒鸡蛋', category: 'lunch' },
  { name: '番茄炒蛋', category: 'lunch' },
  { name: '苦瓜炒肉', category: 'lunch' },
  { name: '豆角炒肉末', category: 'lunch' },
  { name: '茶树菇炒肉', category: 'lunch' },
  { name: '香辣大虾', category: 'lunch' },
  { name: '清蒸鲈鱼', category: 'lunch' },
  { name: '红烧鲫鱼', category: 'lunch' },
  { name: '香煎小黄鱼', category: 'lunch' },
  { name: '爆炒花甲', category: 'lunch' },
  { name: '椒盐基围虾', category: 'lunch' },
  { name: '笋干烧肉', category: 'lunch' },
  { name: '小炒肥肠', category: 'lunch' },
  { name: '酸菜炒大肠', category: 'lunch' },
  { name: '孜然羊肉', category: 'lunch' },
  { name: '黑椒牛柳', category: 'lunch' },
  { name: '菠萝咕咾肉', category: 'lunch' },
  { name: '糖醋里脊', category: 'lunch' },
  { name: '板栗烧鸡', category: 'lunch' },
  { name: '萝卜炖牛腩', category: 'lunch' },
  { name: '玉米炖排骨', category: 'lunch' },
  { name: '扬州炒饭', category: 'lunch' },
  { name: '腊肉炒饭', category: 'lunch' },
  { name: '白切鸡', category: 'lunch' },

  // ===== 晚餐 dinner =====
  { name: '凉拌黄瓜', category: 'dinner' },
  { name: '拍蒜木耳', category: 'dinner' },
  { name: '凉拌海带丝', category: 'dinner' },
  { name: '五香卤豆干', category: 'dinner' },
  { name: '凉拌藕片', category: 'dinner' },
  { name: '盐水花生', category: 'dinner' },
  { name: '凉拌腐竹', category: 'dinner' },
  { name: '爽口萝卜皮', category: 'dinner' },
  { name: '凉拌秋葵', category: 'dinner' },
  { name: '川味口水鸡', category: 'dinner' },
  { name: '夫妻肺片', category: 'dinner' },
  { name: '凉拌猪耳', category: 'dinner' },
  { name: '凉拌三丝', category: 'dinner' },
  { name: '醋泡花生米', category: 'dinner' },
  { name: '凉拌西兰花', category: 'dinner' },
  { name: '香辣毛豆', category: 'dinner' },
  { name: '凉拌土豆丝', category: 'dinner' },
  { name: '卤味拼盘', category: 'dinner' },
  { name: '凉拌金针菇', category: 'dinner' },
  { name: '清炒时蔬', category: 'dinner' },
  { name: '手撕包菜', category: 'dinner' },
  { name: '干煸四季豆', category: 'dinner' },
  { name: '清炒油麦菜', category: 'dinner' },
  { name: '蒜蓉娃娃菜', category: 'dinner' },
  { name: '酸辣土豆丝', category: 'dinner' },
  { name: '香菇青菜', category: 'dinner' },
  { name: '清炒丝瓜', category: 'dinner' },
  { name: '红烧豆腐', category: 'dinner' },
  { name: '麻婆豆腐', category: 'dinner' },
  { name: '韭菜炒香干', category: 'dinner' },
  { name: '炒西葫芦', category: 'dinner' },
  { name: '清炒藕片', category: 'dinner' },
  { name: '冬瓜炒木耳', category: 'dinner' },
  { name: '青椒土豆', category: 'dinner' },
  { name: '炒花菜', category: 'dinner' },
  { name: '红烧茄子', category: 'dinner' },
  { name: '地三鲜', category: 'dinner' },
  { name: '炒荷兰豆', category: 'dinner' },
  { name: '白灼菜心', category: 'dinner' },
  { name: '番茄鸡蛋汤', category: 'dinner' },
  { name: '紫菜蛋花汤', category: 'dinner' },
  { name: '冬瓜排骨汤', category: 'dinner' },
  { name: '海带排骨汤', category: 'dinner' },
  { name: '萝卜牛肉汤', category: 'dinner' },
  { name: '丝瓜蛋汤', category: 'dinner' },
  { name: '菌菇鸡汤', category: 'dinner' },
  { name: '酸辣汤', category: 'dinner' },
  { name: '豆腐鱼头汤', category: 'dinner' },
];

// 附件2：邀请码（一次性使用，用后失效）
export const INVITE_CODES = [
  '7S9K2P5G',
  '3D8F6N4J',
  '2R7T5M9C',
  '6H4V8B2X',
  '9Q5L3Z7E',
  '4W6Y2U8N',
  '5C7B9V3R',
  '8M2P6S4D',
  '2F9G5H7K',
  '7N3J8T5W',
];

// 用餐时段（分钟制）—— 需求第5条
export const TIME_SLOTS = {
  breakfast: { label: '早餐', start: '05:00', end: '10:00', startMin: 5 * 60, endMin: 10 * 60 },
  lunch: { label: '午餐', start: '11:00', end: '13:30', startMin: 11 * 60, endMin: 13 * 60 + 30 },
  dinner: { label: '晚餐', start: '18:00', end: '20:00', startMin: 18 * 60, endMin: 20 * 60 },
};

// 新用户免费次数 / 永久用户每日次数
export const FREE_TRIAL_USES = 5;
export const PERMANENT_DAILY_USES = 3;
